### ISSUE TITLE
DigDeeper not working

### ISSUE THREAD

**Issue by clbx** [CrystalFerrai/ValheimMods#42]
I have DigDeeper version 1.1.6 installed on my dedicated server with BepInEx 5.4.2333

Using the following configuration

```
## Settings file was created by plugin Dig Deeper v1.1.6.0
## Plugin GUID: dev.crystal.digdeeper

[Digging]

## The maximum depth you can dig below the terrain surface. Range 0-128. Game default is 8.
# Setting type: Single
# Default value: 20
MaximumDepth = 120

## The maximum height you can raise the terrain. Range 0-128. Game default is 8.
# Setting type: Single
# Default value: 8
MaximumHeight = 8
```

However, it doesn't seem like I can dig deeper than the vanilla limit. 

<img width="1680" height="1386" alt="Image" src="https://github.com/user-attachments/assets/cbf7a562-2f9a-407f-8f61-86830d756946" />

Thanks

**Comment by CrystalFerrai** [comment]
I just published version 1.1.7 which should make it compatible with the current game version.

**Comment by clbx** [comment]
Thank you for your quick response, but it's still not working. 
I have the same config on 1.1.7 and i still cannot dig below the default height

**Comment by CrystalFerrai** [comment]
I have tested this again and it is still working fine for me. My best guess is there is a client connected to your server with a different config, Make sure all clients are running the mod with the same configuration. I cannot think of any other reason it would not be working.

**Comment by clbx** [comment]
> there is a client connected to your server with a different config

Absolutely correct, thank you for your help!
